ecs522-group4/weather-app

package-lock.json, src/components/Main.jsx
- Implemented the new API, Aerisweather. This one is much more powerful than the previous one.
- Modified the `fetchCurrentWeather` function: it now tidies up the data before storing it.
- Updated the main component to show data based on the new API.
- We now have a great starting point to start implementing a nice GUI.
=> Implemented new API Aerisweather

src/components/Main.jsx
`fetchWeatherFromAPI` now fetches current weather and forecast for the next 23 hours, so we have a 24 hour window we can use for our visualisation.
=> API now fetches forecast

src/components/GeneralData.jsx, src/index.css
For some reason, when moving the slider we were getting an increasing horizontal scroll bar. Fixed that by changing css for body and html.
Also, fixed the behaviour of the slider, now showing 24 data points. 
Fixed its syntax: using `{}` for numbers rather than `""`.
=> Fixed Slider.

src/components/Main.jsx, src/components/Settings.jsx, src/components/TopBar.jsx, src/index.js
We need to share state between two components, Settings and Main. 
With routing these two were not parent/child, hence we should have started using Redux or Mobx or another store. Since this project is very small, we opted to move Settings inside the Main component. We will then use props to share values needed.
=> Removed routing: Settings is now part of Main

src/components/GeneralData.jsx, src/components/Settings.jsx, src/components/TopBar.jsx
- Removed unused variables
- Added default case to switch
=> Code cleanup

package-lock.json, package.json, src/components/LocationSearchbar.jsx, src/components/Main.jsx
Quite a big PR, it was a tough one.
Added a new component: `LocationSearchbar`. As the name suggests, it's a search bar for cities. It auto-completes the users' queries using a free API I found after some research (didn't want to use the Google Maps API which is not free).
**Current Behaviour**
When you connect to the web app, it will fetch weather based on your IP. You can use the search bar to select a city to display the weather for.
=> Added Location search bar

src/components/GeneralData.jsx, src/components/LocationSearchbar.jsx, src/components/Main.jsx
- Fixed the asynch operations, it won't crash anymore due to `undef`
- Added error handling for when users select a city that's not supported by the weather API: the `textfield` will be highlighted in red and a message will be shown.
- Added a loading indicator to notify the user that the app is doing something and it needs time to load
- Added GPS icon at the end of the search bar following design choices
=> Better error handling: Loading, Unsupported place

package-lock.json, package.json, src/components/Calendar.jsx, src/components/GeneralData.jsx, src/components/Main.jsx
- Users can pick a date to display the forecast for (00 am to midnight)
- If forecast is unavailable for that date, an error message is shown
- When switching cities, the date gets reset to today's date
=> Added Calendar to pick date

src/components/GeneralData.jsx, src/components/Main.jsx
Removed state from `GeneralData`. There is now only one source of truth: the state in the `Main `component.
=> GeneralData is now a controlled component

src/assets/icons/arrow.svg, src/components/GeneralData.jsx, src/components/Main.jsx
- Changed display from `flex` to `inline-block` to accommodate arrow next to other weather data
- Added arrow which points to the direction of the wind (following other apps' style, including google weather's visualisation for wind direction)
=> Added arrow to show wind direction

src/components/Calendar.jsx, src/components/GeneralData.jsx, src/components/LocationSearchbar.jsx, src/components/Main.jsx, src/index.css, src/kiteAnimation.css
First attempt at placing components were they belong, following our design document. Previously everything was laying around randomly on the screen.
=> Updated style and adjusted layout

src/components/Main.jsx, src/components/TopBar.jsx
The app is now storing storing:
- Both wind speed and temperature units
- Minimum temperature 
- Minimum wind speed 
- Current city
=> Now using localStorage to save settings

src/components/LocationSearchbar.jsx, src/components/Main.jsx, src/components/TopBar.jsx
The search bar will now display the actual value on startup. It also saves the selected city and will display that in the search bar between sessions and after opening/closing the settings,
=> LocationSearchbar is now synchronised with localStorage

src/components/Main.jsx, src/components/Settings.jsx
- The toggle switch in now synchronised with localStorage
- Update the `checkIfCanFly()` method to take into account the "Day time only" option
=> Implemented logic for "Fly during daytime" option

src/components/Settings.jsx
=> Preventing users from adding leading zeros

src/components/Settings.jsx
There's still plenty of room to improve but hey, this is a University project and we have very limited amount of time.
=> Settings: reduced code repetition

src/components/Main.jsx, src/components/WindVisualisation.jsx
Added a responsive wind visualisation on canvas
=> Wind visualisation

src/components/Calendar.jsx, src/components/LocationSearchbar.jsx, src/components/Main.jsx, src/components/Settings.jsx
.. And turned as much stuff as possible to white.
=> Added Dark Theme style

src/components/Calendar.jsx, src/components/LocationSearchbar.jsx, src/components/Main.jsx
Everything is now white and in place!
=> Further styling to Calendar and LocationSearchbar

src/components/GeneralData.jsx, src/components/Main.jsx, src/components/TopBar.jsx
Fixed minor mistakes the console was complaining about
=> Minor tweaks

src/components/GeneralData.jsx, src/components/Main.jsx
Positioned it in the middle of the screen, coloured it white and increased its size.
=> Styled CircularLoading

src/components/Main.jsx
=> Removed dark palette and made all text white

src/components/GeneralData.jsx, src/components/Main.jsx
Made this change so that the slider can be underneath the wind graph.
=> WindVisualisation is now a child of GeneralData

src/components/Main.jsx, src/components/WindVisualisation.jsx
The selected hour on the slider is now highlighted on the graph and the width of the canvas is dynamically adjusted depending on the window width
=> Wind Graph highlight & dynamical width

src/components/Calendar.jsx, src/components/GeneralData.jsx, src/components/LocationSearchbar.jsx, src/components/TopBar.jsx
Made the slider as wide as the section of the canvas, so the highlighting made by @OlgaLyubin is intuitive
=> Adjusted slider to match the new wind graph size

src/components/LocationSearchbar.jsx
Before this, it was white on white.
=> "No options" message is now black

src/components/GeneralData.jsx, src/components/WindVisualisation.jsx
Refactored code in WindVisualisation component
=> Refactored code for WindVisualisation component

src/components/GeneralData.jsx, src/components/Main.jsx
=> Now displaying the time of the forecast in GeneralData

src/components/GeneralData.jsx, src/components/Main.jsx
Also, changed its colour as white was not visible enough.
=> Slider is now at the bottom of the graph
